FROM 10.219.30.214:5000/dsrs-spark-rhel:v0.3.0-testing-oss

COPY core-1.1.jar /opt/spark-3.0.2/assembly/target/scala-2.12/jars/core-1.1.2.jar
COPY native_system-java-1.1.jar /opt/spark-3.0.2/assembly/target/scala-2.12/jars/native_system-java-1.1.jar
COPY netlib-native_system-linux-x86_64-natives.jar /opt/spark-3.0.2/assembly/target/scala-2.12/jars/netlib-native_system-linux-x86_64-1.1-natives.jar
